name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - name: Typescript + tests + lint
        run: yarn tsc && yarn lint && CI=1 yarn test --passWithNoTests
      - name: Build
        run: yarn build
      - name: Move index.html
        run: mkdir -p build-index && mv build/index.html build-index
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: grbl-explorer-frontend
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build'
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --expires 0 --cache-control 'no-store, must-revalidate' --content-type text/html
        env:
          AWS_S3_BUCKET: grbl-explorer-frontend
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build-index'
